name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: conversao-live
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código fonte do repositório
      uses: actions/checkout@v3.5.2
    - name: Setup ambiente Node.js
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 18.17.0
        cache: 'npm'

    - name: Execução do npm install e o teste
      run: |
        npm install
        npm run test
      working-directory: ./src
