name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: conversao-live
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código fonte do repositório
      uses: actions/checkout@v3.5.2
    - name: Setup ambiente Node.js
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 18.17.0

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Execução do npm install e o teste
      run: |
        cd ./src   # Navega para o diretório onde está o package-lock.json
        npm install
        npm run test

    - name: Construção da imagem do container da aplicação
      uses: docker/build-push-action@v4.0.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          juliumnix/conversao-live:latest
          juliumnix/conversao-live:v${{ github.run_number }}

  deploy:
    name: Deploy
    needs: [CI]
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings        
